# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockersetpgithub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://myregistry11ka.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_73566915abee4bde994c6e057fc8a329 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6b13ddd531814376be63afb1761a486b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: myregistry11ka.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_73566915abee4bde994c6e057fc8a329 }}/maven:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockersetpgithub'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3869f2de934c406bad91ac4e237f077d }}
        images: 'myregistry11ka.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_73566915abee4bde994c6e057fc8a329 }}/maven:${{ github.sha }}'